version: '3'

services:
    django:
        build:
            context: .
            dockerfile: ./docker/python/Dockerfile
        env_file:
            - .env.docker
        volumes:
            - ./:/app
            - static:/static
        ports:
            - "8000:8000"

    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        env_file: .env.docker
        depends_on:
            - django
        volumes:
            - static:/static
            - ./docker/nginx/certs:/certs/:rw
        ports:
            - "80:80"
            - "443:443"

    mailhog:
        image: mailhog/mailhog:latest
        environment:
            - MH_STORAGE=maildir
        ports:
            - "8025:8025"

volumes:
    static:
